namespace Windows_Sound_Changer
{
    class Preset
    {
        public string? Name { get; set; }
        public string? FileName { get; set; }

        public static List<Preset> Windows11 { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Background.wav" },
            new() { Name = "Notification.Reminder", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify Calendar.wav" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Foreground.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Background.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify Email.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = "" },
            new() { Name = "Notification.IM", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify Messaging.wav" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Message Nudge.wav" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify Email.wav" },
            new() { Name = "Notification.Mail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify Email.wav" },
            new() { Name = "Notification.SMS" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify Messaging.wav" },
            new() { Name = "Notification.Proximity", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Proximity Notification.wav" },
            new() { Name = "ProximityConnection", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Proximity Connection.wav" },
            new() { Name = "Notification.Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Notify System Generic.wav"},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Background.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = "" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Logon.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows Logoff.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 11\Windows User Account Control.wav" }
        };
        public static List<Preset> Windows10 { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Background.wav" },
            new() { Name = "Notification.Reminder", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify Calendar.wav" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Foreground.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Background.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify Email.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = "" },
            new() { Name = "Notification.IM", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify Messaging.wav" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Message Nudge.wav" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify Email.wav" },
            new() { Name = "Notification.Mail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify Email.wav" },
            new() { Name = "Notification.SMS" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify Messaging.wav" },
            new() { Name = "Notification.Proximity", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Proximity Notification.wav" },
            new() { Name = "ProximityConnection", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Proximity Connection.wav" },
            new() { Name = "Notification.Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Notify System Generic.wav"},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Background.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = "" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Logon.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows Logoff.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 10\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7 { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Afternoon { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Afternoon\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Calligraphy { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Calligraphy\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Characters { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Characters\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Cityscape { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Cityscape\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Delta { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Delta\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Festival { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Festival\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Garden { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Garden\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Heritage { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Heritage\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Landscape { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Landscape\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Quirky { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Quirky\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Raga { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Raga\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Savanna { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Savanna\Windows User Account Control.wav"}
        };
        public static List<Preset> Windows7_Sonata { get; } = new()
        {
            new() { Name = "SystemAsterisk", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Error.wav" },
            new() { Name = "Notification.Reminder", FileName = "" },
            new() { Name = "Close", FileName = "" },
            new() { Name = "CriticalBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Battery Critical.wav" },
            new() { Name = "SystemHand", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Critical Stop.wav" },
            new() { Name = ".Default", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Ding.wav" },
            new() { Name = "MailBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Notify.wav" },
            new() { Name = "DeviceConnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Hardware Insert.wav" },
            new() { Name = "DeviceDisconnect", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Hardware Remove.wav" },
            new() { Name = "DeviceFail", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Hardware Fail.wav" },
            new() { Name = "SystemExclamation", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Exclamation.wav" },
            new() { Name = "SystemExit", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Windows Shutdown.wav" },
            new() { Name = "Notification.IM", FileName = "" },
            new() { Name = "LowBatteryAlarm", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Battery Low.wav" },
            new() { Name = "Maximize", FileName = "" },
            new() { Name = "MenuCommand", FileName = "" },
            new() { Name = "MenuPopup", FileName = "" },
            new() { Name = "MessageNudge", FileName = "" },
            new() { Name = "Minimize", FileName = "" },
            new() { Name = "FaxBeep", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Notify.wav" },
            new() { Name = "Notification.Mail", FileName = "" },
            new() { Name = "Notification.SMS" , FileName = "" },
            new() { Name = "Notification.Proximity", FileName = "" },
            new() { Name = "ProximityConnection", FileName = "" },
            new() { Name = "Notification.Default", FileName = ""},
            new() { Name = "Open", FileName = "" },
            new() { Name = "CCSelect", FileName = ""},
            new() { Name = "PrintComplete", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Print complete.wav" },
            new() { Name = "AppGPFault" , FileName = ""},
            new() { Name = "SystemQuestion", FileName = "" },
            new() { Name = "RestoreDown", FileName = "" },
            new() { Name = "RestoreUp" , FileName = "" },
            new() { Name = "SystemNotification", FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Balloon.wav" },
            new() { Name = "ShowBand" , FileName = "" },
            new() { Name = "ChangeTheme" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogon" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Logon Sound.wav" },
            new() { Name = "WindowsLogoff" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows Logoff Sound.wav" },
            new() { Name = "WindowsUAC" , FileName = @$"{Environment.CurrentDirectory}\sounds\Windows 7\Sonata\Windows User Account Control.wav"}
        };
    }
}